### ISSUE TITLE
Can't use build target with TM_ANT_BUILD_FILE

### ISSUE THREAD

**Issue by artsyca** [textmate/ant.tmbundle#1]
Hello,
Thank you very much for this excellent plugin, it is very useful in my daily workflow with Java. I can't seem to get 'build target' to work with TM_ANT_BUILD_FILE at all.

No matter what I do, I get the following error:

/tmp/temp_textmate.hAbmHS:27: undefined method `+' for nil:NilClass (NoMethodError)

I have set TM_ANT_BUILD_FILE to build.xml which is at the root of my project directory, but this command will not work at all whether it's run with the file selected or not. I suspect it may be an issue with my installation of ruby or ant. I'm very sorry if this is the case.

Your help is appreciated.

Alexandros

**Comment by simongregory** [comment]
I've just tried this and, when I set TM_ANT_BUILD_FILE and introduce extra scopes (ie text.xml.mxml) to the 'Build Target' command it's working. The error you're seeing suggests to me that there's a problem when the command is trying to construct the path to the build.xml file. 

Are you running the command from a TextMate project?

**Comment by artsyca** [comment]
Thanks very much for your reply. Here are some more specifics 
- build.xml is at the root of the project and the whole project is open in textmate (in the drawer).
- by default, the 'Build' command works no matter what file is currently open. 'Build Target' only works when build.xml is open.
- setting TM_ANT_BUILD_FILE=build.xml has no effect on 'Build'; It totally crashes 'Build Target' however.. it stops working whether build.xml is selected or not. It also crashes 'List Targets'

In writing this, I realize I may be mistaken as to which value I should put for TM_ANT_BUILD_FILE. I just assumed it would be the filename of the build file. Currently my build file resides in TM_PROJECT_DIRECTORY/TM_ANT_BUILD_FILE 
.. ie project/build.xml.

I'm sorry to say I don't know enough about ruby, textmate or ant to offer a better diagnosis.

**Comment by artsyca** [comment]
I did a bit more digging, and it seems like TM_PROJECT_FILEPATH is coming through as nil.

I tried replacing it with TM_PROJECT_DIRECTORY but for whatever reason, that comes back as the _parent_ of the current project.. ie path/to/project/build.xml and TM_PROJECT_DIRECTORY is coming up as path/to/. That doesn't make much sense at all I'm afraid, as it even says in the [textmate documentation](http://manual.macromates.com/en/environment_variables.html) that it should be: 

> TM_PROJECT_DIRECTORY — the top-level folder in the project drawer (may not be set).

**Comment by artsyca** [comment]
OH! and a bit of further research: http://fuerstnet.de/en/ftp-ssh-bundle-textmate#comment-42

Apparently I was completely unaware of the notion of a "project" .. I have only ever dragged folders into textmate to create ad-hoc projects. So it seems that it only works with a real project, not an ad-hoc one.. go figure!

**Comment by simongregory** [comment]
Glad to see that you now have this working. I will take a look at the help documentation and make it clearer that you have to have a saved project for this to work.
